spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:50}
            redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:150}
      httpclient:
        pool:
          type: elastic
          max-connections: ${GATEWAY_MAX_CONNECTIONS:500}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
logging:
  level:
    org.springframework.cloud.gateway: INFO
