spring:
  main:
    banner-mode: "off"
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      roles: ADMIN
    prometheus:
      enabled: true
  metrics:
    tags:
      application: marketplace
logging:
  level:
    root: INFO
    org.springframework.cloud: WARN
    org.springframework.web: INFO
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 10
        slowCallRateThreshold: 60
        slowCallDurationThreshold: 2s
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
springdoc:
  swagger-ui:
    enabled: true
    tags-sorter: alpha
  api-docs:
    enabled: true
