spring:
  profiles: prod
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://auth-db:5432/auth_db}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${AUTH_DB_MAX_POOL_SIZE:20}
      minimum-idle: 5
  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTH_JWT_ISSUER:https://auth.marketplace.com}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    root: INFO
auth:
  jwt:
    private-key: ${AUTH_JWT_PRIVATE_KEY}
    public-key: ${AUTH_JWT_PUBLIC_KEY}
