server:
  port: 0
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${AUTH_DB_USERNAME:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_pass}
    hikari:
      maximum-pool-size: ${AUTH_DB_MAX_POOL_SIZE:10}
      minimum-idle: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTH_JWT_ISSUER:http://localhost:9000}
        token-endpoint:
          access-token-time-to-live: ${AUTH_ACCESS_TOKEN_TTL:PT15M}
          refresh-token-time-to-live: ${AUTH_REFRESH_TOKEN_TTL:P30D}
        client-settings:
          require-authorization-consent: false
auth:
  jwt:
    private-key: ${AUTH_JWT_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----\n...}
    public-key: ${AUTH_JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\n...}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.marketplace.auth: INFO
