spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_BRANCH:main}
          clone-on-start: true
          skip-ssl-validation: ${CONFIG_GIT_SKIP_SSL:false}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,busrefresh,env
