server:
  port: 0
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        linger.ms: 5
        compression.type: zstd
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.marketplace.notification: INFO
notification:
  channels:
    email:
      enabled: true
    sms:
      enabled: ${NOTIFICATION_SMS_ENABLED:false}
    push:
      enabled: ${NOTIFICATION_PUSH_ENABLED:false}
  templates:
    base-path: ${NOTIFICATION_TEMPLATES_PATH:classpath:/templates/notifications}
