spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://payment-db:5432/payment_db}
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${PAYMENT_DB_MAX_POOL_SIZE:20}
      minimum-idle: 5
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            security.protocol: SASL_SSL
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG}
      bindings:
        settlement-out-0:
          destination: payment.settlement
        refund-out-0:
          destination: payment.refund
logging:
  level:
    root: INFO
payment:
  provider:
    stripe:
      api-key: ${STRIPE_API_KEY}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET}
    paypal:
      client-id: ${PAYPAL_CLIENT_ID}
      client-secret: ${PAYPAL_CLIENT_SECRET}
  integrations:
    order-service:
      base-url: ${ORDER_SERVICE_URL:https://order.marketplace.internal}
