spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5432/product_db_dev}
    username: ${PRODUCT_DB_USERNAME:product_user}
    password: ${PRODUCT_DB_PASSWORD:product_pass}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: DEBUG
product:
  media:
    base-url: http://localhost:9000/products
