server:
  port: 0
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${PRODUCT_DB_USERNAME:product_user}
    password: ${PRODUCT_DB_PASSWORD:product_pass}
    hikari:
      maximum-pool-size: ${PRODUCT_DB_MAX_POOL_SIZE:10}
      minimum-idle: 3
      connection-timeout: 25000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2s
cloud:
  aws:
    s3:
      bucket: ${PRODUCT_ASSETS_BUCKET:marketplace-product-assets}
management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    db:
      enabled: true
logging:
  level:
    com.marketplace.product: DEBUG
product:
  media:
    base-url: ${PRODUCT_MEDIA_BASE_URL:https://cdn.marketplace.local/products}
  search:
    page-size: 12
