spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://product-db:5432/product_db}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${PRODUCT_DB_MAX_POOL_SIZE:15}
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    ssl: ${REDIS_SSL:true}
logging:
  level:
    root: INFO
product:
  media:
    base-url: https://cdn.marketplace.com/products
