server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${USER_DB_USERNAME:user_user}
    password: ${USER_DB_PASSWORD:user_pass}
    hikari:
      maximum-pool-size: ${USER_DB_MAX_POOL_SIZE:10}
      minimum-idle: 3
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_JWT_ISSUER_URI:http://localhost:8081/realms/marketplace}
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
logging:
  level:
    com.marketplace.user: INFO
user:
  avatar-storage:
    provider: s3
    bucket: ${USER_AVATAR_BUCKET:marketplace-user-avatars}
  default-roles:
    - ROLE_CUSTOMER
