spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://user-db:5432/user_db}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${USER_DB_MAX_POOL_SIZE:20}
      minimum-idle: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_JWT_ISSUER_URI:https://auth.marketplace.com/realms/marketplace}
user:
  avatar-storage:
    provider: s3
    bucket: ${USER_AVATAR_BUCKET}
    base-url: ${USER_AVATAR_BASE_URL:https://cdn.marketplace.com/avatars}
